export const driver = [
  {
    background: "/driver1.png",
    firstName: "Max",
    lastName: "Verstappen",
    countryFlag: "/india.png",
    team: "Red Bull Racing",
    country: "Netherlands",
  },
  {
    background: "/driver2.png",
    firstName: "Max",
    lastName: "Verstappen",
    countryFlag: "/india.png",
    team: "Red Bull Racing",
    country: "Netherlands",
  },
  {
    background: "/driver3.png",
    firstName: "Max",
    lastName: "Verstappen",
    countryFlag: "/india.png",
    team: "Red Bull Racing",
    country: "Netherlands",
  },
  {
    background: "/driver4.png",
    firstName: "Max",
    lastName: "Verstappen",
    countryFlag: "/india.png",
    team: "Red Bull Racing",
    country: "Netherlands",
  },
  {
    background: "/driver5.png",
    firstName: "Max",
    lastName: "Verstappen",
    countryFlag: "/india.png",
    team: "Red Bull Racing",
    country: "Netherlands",
  },
  {
    background: "/driver6.png",
    firstName: "Max",
    lastName: "Verstappen",
    countryFlag: "/india.png",
    team: "Red Bull Racing",
    country: "Netherlands",
  },
  {
    background: "/driver7.png",
    firstName: "Max",
    lastName: "Verstappen",
    countryFlag: "/india.png",
    team: "Red Bull Racing",
    country: "Netherlands",
  },
  {
    background: "/driver8.png",
    firstName: "Max",
    lastName: "Verstappen",
    countryFlag: "/india.png",
    team: "Red Bull Racing",
    country: "Netherlands",
  },
  {
    background: "/driver9.png",
    firstName: "Max",
    lastName: "Verstappen",
    countryFlag: "/india.png",
    team: "Red Bull Racing",
    country: "Netherlands",
  },
  {
    background: "/driver10.png",
    firstName: "Max",
    lastName: "Verstappen",
    countryFlag: "/india.png",
    team: "Red Bull Racing",
    country: "Netherlands",
  },
  {
    background: "/driver11.png",
    firstName: "Max",
    lastName: "Verstappen",
    countryFlag: "/india.png",
    team: "Red Bull Racing",
    country: "Netherlands",
  },
  {
    background: "/driver12.png",
    firstName: "Max",
    lastName: "Verstappen",
    countryFlag: "/india.png",
    team: "Red Bull Racing",
    country: "Netherlands",
  },
  {
    background: "/driver13.png",
    firstName: "Max",
    lastName: "Verstappen",
    countryFlag: "/india.png",
    team: "Red Bull Racing",
    country: "Netherlands",
  },
  {
    background: "/driver14.png",
    firstName: "Max",
    lastName: "Verstappen",
    countryFlag: "/india.png",
    team: "Red Bull Racing",
    country: "Netherlands",
  },
  {
    background: "/driver15.png",
    firstName: "Max",
    lastName: "Verstappen",
    countryFlag: "/india.png",
    team: "Red Bull Racing",
    country: "Netherlands",
  },
  {
    background: "/driver16.png",
    firstName: "Max",
    lastName: "Verstappen",
    countryFlag: "/india.png",
    team: "Red Bull Racing",
    country: "Netherlands",
  },
  {
    background: "/driver17.png",
    firstName: "Max",
    lastName: "Verstappen",
    countryFlag: "/india.png",
    team: "Red Bull Racing",
    country: "Netherlands",
  },
  {
    background: "/driver18.png",
    firstName: "Max",
    lastName: "Verstappen",
    countryFlag: "/india.png",
    team: "Red Bull Racing",
    country: "Netherlands",
  },
  {
    background: "/driver19.png",
    firstName: "Max",
    lastName: "Verstappen",
    countryFlag: "/india.png",
    team: "Red Bull Racing",
    country: "Netherlands",
  },
  {
    background: "/driver20.png",
    firstName: "Max",
    lastName: "Verstappen",
    countryFlag: "/india.png",
    team: "Red Bull Racing",
    country: "Netherlands",
  },
  {
    background: "/driver21.png",
    firstName: "Max",
    lastName: "Verstappen",
    countryFlag: "/india.png",
    team: "Red Bull Racing",
    country: "Netherlands",
  },
];

export const unlistedDriver = [
  {
    background: "/driver1.png",
    firstName: "Max",
    lastName: "Verstappen",
    countryFlag: "/india.png",
    team: "Red Bull Racing",
    country: "Netherlands",
  },
  {
    background: "/driver2.png",
    firstName: "Max",
    lastName: "Verstappen",
    countryFlag: "/india.png",
    team: "Red Bull Racing",
    country: "Netherlands",
  },
  {
    background: "/driver3.png",
    firstName: "Max",
    lastName: "Verstappen",
    countryFlag: "/india.png",
    team: "Red Bull Racing",
    country: "Netherlands",
  },
  {
    background: "/driver4.png",
    firstName: "Max",
    lastName: "Verstappen",
    countryFlag: "/india.png",
    team: "Red Bull Racing",
    country: "Netherlands",
  },
  {
    background: "/driver5.png",
    firstName: "Max",
    lastName: "Verstappen",
    countryFlag: "/india.png",
    team: "Red Bull Racing",
    country: "Netherlands",
  },
  {
    background: "/driver6.png",
    firstName: "Max",
    lastName: "Verstappen",
    countryFlag: "/india.png",
    team: "Red Bull Racing",
    country: "Netherlands",
  },
  {
    background: "/driver7.png",
    firstName: "Max",
    lastName: "Verstappen",
    countryFlag: "/india.png",
    team: "Red Bull Racing",
    country: "Netherlands",
  },
  {
    background: "/driver8.png",
    firstName: "Max",
    lastName: "Verstappen",
    countryFlag: "/india.png",
    team: "Red Bull Racing",
    country: "Netherlands",
  },
  {
    background: "/driver9.png",
    firstName: "Max",
    lastName: "Verstappen",
    countryFlag: "/india.png",
    team: "Red Bull Racing",
    country: "Netherlands",
  },
  {
    background: "/driver10.png",
    firstName: "Max",
    lastName: "Verstappen",
    countryFlag: "/india.png",
    team: "Red Bull Racing",
    country: "Netherlands",
  },
  {
    background: "/driver11.png",
    firstName: "Max",
    lastName: "Verstappen",
    countryFlag: "/india.png",
    team: "Red Bull Racing",
    country: "Netherlands",
  },
];
